name: keda-ec

services:
  app:
    build:
      context: ./app
    environment:
      APP_BASE_URL: http://localhost:8080
      APP_SESSION_SECRET: change-me-in-lab
      APP_CORS_MODE: secure
      APP_ERROR_DETAIL: "0"
      APP_AUTHZ_ENFORCE_TENANT: "1"
      APP_AUTHZ_ENFORCE_OWNER: "0"
    ports:
      - "8080:8080"
    volumes:
      - app_data:/data

volumes:
  app_data:

